@@ .. @@
 INSERT INTO indicator_values (
   organization_name,
-  business_line_key,
-  subsidiary_key,
-  site_key,
   business_line_name,
   subsidiary_name,
   site_name,
   process_code,
   indicator_code,
   year,
   month,
   value,
   status,
   submitted_by,
   validated_by,
   validated_at
 ) VALUES
   -- Site Abidjan - Janvier 2025
-  ('TestFiliere', '', '', 'Abidjan', NULL, NULL, 'Abidjan', 'INFO_GEN', 'B1_CA', 2025, 1, 15000000, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
-  ('TestFiliere', '', '', 'Abidjan', NULL, NULL, 'Abidjan', 'INFO_GEN', 'B1_SITES', 2025, 1, 1, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
-  ('TestFiliere', '', '', 'Abidjan', NULL, NULL, 'Abidjan', 'STRAT_AFF', 'C1_ACHAT_LOC', 2025, 1, 75, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
-  ('TestFiliere', '', '', 'Abidjan', NULL, NULL, 'Abidjan', 'GOUVERNANCE', 'C3_MEMBRES_CA', 2025, 1, 9, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
-  ('TestFiliere', '', '', 'Abidjan', NULL, NULL, 'Abidjan', 'RH_EMPLOI', 'S1_CDI_FEMMES', 2025, 1, 45, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
-  ('TestFiliere', '', '', 'Abidjan', NULL, NULL, 'Abidjan', 'REMUNERATION', 'B10_SAL_ENTREE', 2025, 1, 350000, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
+  ('TestFiliere', NULL, NULL, 'Abidjan', 'INFO_GEN', 'B1_CA', 2025, 1, 15000000, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
+  ('TestFiliere', NULL, NULL, 'Abidjan', 'INFO_GEN', 'B1_SITES', 2025, 1, 1, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
+  ('TestFiliere', NULL, NULL, 'Abidjan', 'STRAT_AFF', 'C1_ACHAT_LOC', 2025, 1, 75, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
+  ('TestFiliere', NULL, NULL, 'Abidjan', 'GOUVERNANCE', 'C3_MEMBRES_CA', 2025, 1, 9, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
+  ('TestFiliere', NULL, NULL, 'Abidjan', 'RH_EMPLOI', 'S1_CDI_FEMMES', 2025, 1, 45, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
+  ('TestFiliere', NULL, NULL, 'Abidjan', 'REMUNERATION', 'B10_SAL_ENTREE', 2025, 1, 350000, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
 
   -- Site Yamoussoukro - Janvier 2025
-  ('TestFiliere', '', '', 'Yamoussoukro', NULL, NULL, 'Yamoussoukro', 'INFO_GEN', 'B1_CA', 2025, 1, 8000000, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
-  ('TestFiliere', '', '', 'Yamoussoukro', NULL, NULL, 'Yamoussoukro', 'INFO_GEN', 'B1_SITES', 2025, 1, 1, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
-  ('TestFiliere', '', '', 'Yamoussoukro', NULL, NULL, 'Yamoussoukro', 'STRAT_AFF', 'C1_ACHAT_LOC', 2025, 1, 80, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
-  ('TestFiliere', '', '', 'Yamoussoukro', NULL, NULL, 'Yamoussoukro', 'GOUVERNANCE', 'C3_MEMBRES_CA', 2025, 1, 9, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
-  ('TestFiliere', '', '', 'Yamoussoukro', NULL, NULL, 'Yamoussoukro', 'RH_EMPLOI', 'S1_CDI_FEMMES', 2025, 1, 32, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
-  ('TestFiliere', '', '', 'Yamoussoukro', NULL, NULL, 'Yamoussoukro', 'REMUNERATION', 'B10_SAL_ENTREE', 2025, 1, 320000, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
+  ('TestFiliere', NULL, NULL, 'Yamoussoukro', 'INFO_GEN', 'B1_CA', 2025, 1, 8000000, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
+  ('TestFiliere', NULL, NULL, 'Yamoussoukro', 'INFO_GEN', 'B1_SITES', 2025, 1, 1, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
+  ('TestFiliere', NULL, NULL, 'Yamoussoukro', 'STRAT_AFF', 'C1_ACHAT_LOC', 2025, 1, 80, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
+  ('TestFiliere', NULL, NULL, 'Yamoussoukro', 'GOUVERNANCE', 'C3_MEMBRES_CA', 2025, 1, 9, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
+  ('TestFiliere', NULL, NULL, 'Yamoussoukro', 'RH_EMPLOI', 'S1_CDI_FEMMES', 2025, 1, 32, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
+  ('TestFiliere', NULL, NULL, 'Yamoussoukro', 'REMUNERATION', 'B10_SAL_ENTREE', 2025, 1, 320000, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
 
   -- Site Bouaké - Février 2025
-  ('TestFiliere', '', '', 'Bouaké', NULL, NULL, 'Bouaké', 'INFO_GEN', 'B1_CA', 2025, 2, 12000000, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
-  ('TestFiliere', '', '', 'Bouaké', NULL, NULL, 'Bouaké', 'INFO_GEN', 'B1_SITES', 2025, 2, 1, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
-  ('TestFiliere', '', '', 'Bouaké', NULL, NULL, 'Bouaké', 'STRAT_AFF', 'C1_ACHAT_LOC', 2025, 2, 70, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
-  ('TestFiliere', '', '', 'Bouaké', NULL, NULL, 'Bouaké', 'GOUVERNANCE', 'C3_MEMBRES_CA', 2025, 2, 9, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
-  ('TestFiliere', '', '', 'Bouaké', NULL, NULL, 'Bouaké', 'RH_EMPLOI', 'S1_CDI_FEMMES', 2025, 2, 28, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
-  ('TestFiliere', '', '', 'Bouaké', NULL, NULL, 'Bouaké', 'REMUNERATION', 'B10_SAL_ENTREE', 2025, 2, 340000, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
+  ('TestFiliere', NULL, NULL, 'Bouaké', 'INFO_GEN', 'B1_CA', 2025, 2, 12000000, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
+  ('TestFiliere', NULL, NULL, 'Bouaké', 'INFO_GEN', 'B1_SITES', 2025, 2, 1, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
+  ('TestFiliere', NULL, NULL, 'Bouaké', 'STRAT_AFF', 'C1_ACHAT_LOC', 2025, 2, 70, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
+  ('TestFiliere', NULL, NULL, 'Bouaké', 'GOUVERNANCE', 'C3_MEMBRES_CA', 2025, 2, 9, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
+  ('TestFiliere', NULL, NULL, 'Bouaké', 'RH_EMPLOI', 'S1_CDI_FEMMES', 2025, 2, 28, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
+  ('TestFiliere', NULL, NULL, 'Bouaké', 'REMUNERATION', 'B10_SAL_ENTREE', 2025, 2, 340000, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
 
   -- Site San Pedro - Mars 2025
-  ('TestFiliere', '', '', 'San Pedro', NULL, NULL, 'San Pedro', 'INFO_GEN', 'B1_CA', 2025, 3, 10000000, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
-  ('TestFiliere', '', '', 'San Pedro', NULL, NULL, 'San Pedro', 'INFO_GEN', 'B1_SITES', 2025, 3, 1, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
-  ('TestFiliere', '', '', 'San Pedro', NULL, NULL, 'San Pedro', 'STRAT_AFF', 'C1_ACHAT_LOC', 2025, 3, 85, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
-  ('TestFiliere', '', '', 'San Pedro', NULL, NULL, 'San Pedro', 'GOUVERNANCE', 'C3_MEMBRES_CA', 2025, 3, 9, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
-  ('TestFiliere', '', '', 'San Pedro', NULL, NULL, 'San Pedro', 'RH_EMPLOI', 'S1_CDI_FEMMES', 2025, 3, 38, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
-  ('TestFiliere', '', '', 'San Pedro', NULL, NULL, 'San Pedro', 'REMUNERATION', 'B10_SAL_ENTREE', 2025, 3, 360000, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW());
+  ('TestFiliere', NULL, NULL, 'San Pedro', 'INFO_GEN', 'B1_CA', 2025, 3, 10000000, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
+  ('TestFiliere', NULL, NULL, 'San Pedro', 'INFO_GEN', 'B1_SITES', 2025, 3, 1, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
+  ('TestFiliere', NULL, NULL, 'San Pedro', 'STRAT_AFF', 'C1_ACHAT_LOC', 2025, 3, 85, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
+  ('TestFiliere', NULL, NULL, 'San Pedro', 'GOUVERNANCE', 'C3_MEMBRES_CA', 2025, 3, 9, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
+  ('TestFiliere', NULL, NULL, 'San Pedro', 'RH_EMPLOI', 'S1_CDI_FEMMES', 2025, 3, 38, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW()),
+  ('TestFiliere', NULL, NULL, 'San Pedro', 'REMUNERATION', 'B10_SAL_ENTREE', 2025, 3, 360000, 'validated', 'admin@testfiliere.com', 'validator@testfiliere.com', NOW());